name: grade_calculator
description: "A professional Flutter application for automating student grade calculations."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  excel: ^4.0.3
  file_picker: ^8.0.0+1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  share_plus: ^7.2.2
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/grading_image.jpg
